level = [

        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                                                                                                                                                                                                                                                                                                 P",
        "P                                                                                                                                                                                                                                                                                                                                                 P",
        "P                                                                                                                                                                                                                                                                                                                                                 P",
        "P                                                                                                                                                                                                                                                                                                                                                 P",
        "P                                                                                                                                                                                                                                                                                                                                                 P",
        "P                                                                                                                                                                                                                                                                                                                                                 P",
        "P                                                                                                                                                                                                                                                                                                                   P                             P",
        "P                                                                                                                                                                                                                             PP                                                                                                                  P",
        "P                                                                                                                                                                                                                                                                                                                   P P P  P P  PPP               P",
        "P                                                                                                                                                                                                                       PPP                                                                                         P P P P P P P P               P",
        "P                                                                                                                                                                                                          PPP                                                                                                      P PPP P   P PPP               P",
        "P                                                                                                                                                                                                                                                                                                                  P            P                 P",
        "P                                                                                                                                                                 P                      P                        PPP                                                                                                           P                 P",
        "P                                                                                                                                                                 P           P          P          PPP                             PPPPPPP                                                   PPPPPPPPPP                                          P",
        "P                                                                                                                                                                 P           P          P                                                                                                   PPPPP      PPPPPP                                    P",
        "P                                        PPPPPPPPP                                                                                                     PPPPPP     P    E      PPPPPPPPPPPP                                                                        PPP                       PPPPPPP           PPPP                                P",
        "P                                                                                                                                                  P              PPPPPPPPPPPPP                                                               PPPP                                         PPPPPPPPP              PPP                             P",
        "P                          PPPPPP                                                                      PPPPP                                P                                                                                                                    EEEEE  PPPP              PPPPPPPPPPP                                             P",
        "P                       PPPEEEEEE                                       PPPP               PPPP        EEEEE                       PPPP                                                                                                              PPPP     PPP                        PPPPPPPPPPPPP                                            P",
        "P                  PPEEEEEEEEEEEE                                                                                                                                                                                                                                                       PPPPPPPPPPPPPPP                                           P",
        "P                 EEEEEEEEEEEEEEEE      E                    EE                       E   E                       P         PP                                                                         P                                                                               PPPPPPPPPPPPPPPPP                                          P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPEEEEEEPPPPPPPPPPPPPPPPPPPPPPPPPPPEEEPPPPPPPPPEEEPPPPPPPPPPPPPEEEEEEEEPPPPPPPPPPPPEEEEEEEEEPPPPPPPEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEPPPPPPPPPPPPPPPPPPPPPPPPPPPP                                         P",
        ]




